cache:
  paths:
    - node_modules/

deploy:
  only:
    - develop@vijay/feed-docs
  image: code.qburst.com:4567/vijay/feed-docs:v2
  tags:
    - QBC-internal
  stage: deploy
  environment: Live
  script:
    - yarn install
    - yarn test
    - yarn run build
    - cd build/
    - ls
    - export SSHPASS=$SSH_PASSWORD
    - sshpass -e scp -r -o StrictHostKeyChecking=no * feed-docs@34.224.118.158:/home/feed-docs/public_html
